### ISSUE TITLE
error in data generator

### ISSUE THREAD

**Issue by wuyingfeng1hao** [mspnp/azure-stream-analytics-data-pipeline#3]
The error occurred when I run the data generator using "docker run -v D:/AZure/azure-stream-analytics-data-pipeline-master/DataFile:/DataFile --env-file=onprem/main.env dataloader:latest", but it failed for an error as below,

Created 10000 records for TaxiFare
No such device or address
event hub client failed for TaxiFare
No such device or address
event hub client failed for TaxiRide
No such device or address
event hub client failed for TaxiRide
No such device or address
event hub client failed for TaxiFare
No such device or address
event hub client failed for TaxiRide
No such device or address
event hub client failed for TaxiRide
......
A task was canceled.
Data generation failed

**Comment by v-fearam** [comment]
Hi @wuyingfeng1hao,

I have already looked and I didn't get the "failure" you are currently experiencing.
I guess it is because of the location of the data files. 
I would like to highlight Step 4, the /DataFile directory should be in the root directory of the GitHub repository
Let me know if you need more help

Regards

**Comment by v-fearam** [comment]
I will close the ticket as far as I am not able to reproduce, but feel free to re-open if you considered
